# Generated by Django 5.2 on 2025-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_app', '0002_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='post_permission',
            field=models.CharField(choices=[('admins_only', 'Admins only'), ('everyone', 'All members')], default='admins_only', max_length=15),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice')], default='text', max_length=10),
        ),
    ]
