# Generated by Django 5.2 on 2025-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_app', '0003_alter_channel_post_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_channel/'),
        ),
    ]
